package com.youranxue.domain.mapper;

import com.youranxue.domain.model.TestGroupTrn;
import com.youranxue.domain.model.TestGroupTrnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestGroupTrnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	long countByExample(TestGroupTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int deleteByExample(TestGroupTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int deleteByPrimaryKey(Long testGroupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int insert(TestGroupTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int insertSelective(TestGroupTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	List<TestGroupTrn> selectByExample(TestGroupTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	TestGroupTrn selectByPrimaryKey(Long testGroupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByExampleSelective(@Param("record") TestGroupTrn record, @Param("example") TestGroupTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByExample(@Param("record") TestGroupTrn record, @Param("example") TestGroupTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByPrimaryKeySelective(TestGroupTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_group_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByPrimaryKey(TestGroupTrn record);
}