package com.youranxue.domain.mapper;

import com.youranxue.domain.model.TestTrn;
import com.youranxue.domain.model.TestTrnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTrnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	long countByExample(TestTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int deleteByExample(TestTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int deleteByPrimaryKey(Long testId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int insert(TestTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int insertSelective(TestTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	List<TestTrn> selectByExample(TestTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	TestTrn selectByPrimaryKey(Long testId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByExampleSelective(@Param("record") TestTrn record, @Param("example") TestTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByExample(@Param("record") TestTrn record, @Param("example") TestTrnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByPrimaryKeySelective(TestTrn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.test_trn
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	int updateByPrimaryKey(TestTrn record);
}