package com.youranxue.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CourseTrnExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public CourseTrnExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andCourseIdIsNull() {
			addCriterion("course_id is null");
			return (Criteria) this;
		}

		public Criteria andCourseIdIsNotNull() {
			addCriterion("course_id is not null");
			return (Criteria) this;
		}

		public Criteria andCourseIdEqualTo(String value) {
			addCriterion("course_id =", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotEqualTo(String value) {
			addCriterion("course_id <>", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdGreaterThan(String value) {
			addCriterion("course_id >", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdGreaterThanOrEqualTo(String value) {
			addCriterion("course_id >=", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdLessThan(String value) {
			addCriterion("course_id <", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdLessThanOrEqualTo(String value) {
			addCriterion("course_id <=", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdLike(String value) {
			addCriterion("course_id like", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotLike(String value) {
			addCriterion("course_id not like", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdIn(List<String> values) {
			addCriterion("course_id in", values, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotIn(List<String> values) {
			addCriterion("course_id not in", values, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdBetween(String value1, String value2) {
			addCriterion("course_id between", value1, value2, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotBetween(String value1, String value2) {
			addCriterion("course_id not between", value1, value2, "courseId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdIsNull() {
			addCriterion("subject_id is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIdIsNotNull() {
			addCriterion("subject_id is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectIdEqualTo(Integer value) {
			addCriterion("subject_id =", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdNotEqualTo(Integer value) {
			addCriterion("subject_id <>", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdGreaterThan(Integer value) {
			addCriterion("subject_id >", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("subject_id >=", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdLessThan(Integer value) {
			addCriterion("subject_id <", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
			addCriterion("subject_id <=", value, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdIn(List<Integer> values) {
			addCriterion("subject_id in", values, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdNotIn(List<Integer> values) {
			addCriterion("subject_id not in", values, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
			addCriterion("subject_id between", value1, value2, "subjectId");
			return (Criteria) this;
		}

		public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
			addCriterion("subject_id not between", value1, value2, "subjectId");
			return (Criteria) this;
		}

		public Criteria andGradeIdIsNull() {
			addCriterion("grade_id is null");
			return (Criteria) this;
		}

		public Criteria andGradeIdIsNotNull() {
			addCriterion("grade_id is not null");
			return (Criteria) this;
		}

		public Criteria andGradeIdEqualTo(Integer value) {
			addCriterion("grade_id =", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdNotEqualTo(Integer value) {
			addCriterion("grade_id <>", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdGreaterThan(Integer value) {
			addCriterion("grade_id >", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("grade_id >=", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdLessThan(Integer value) {
			addCriterion("grade_id <", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdLessThanOrEqualTo(Integer value) {
			addCriterion("grade_id <=", value, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdIn(List<Integer> values) {
			addCriterion("grade_id in", values, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdNotIn(List<Integer> values) {
			addCriterion("grade_id not in", values, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdBetween(Integer value1, Integer value2) {
			addCriterion("grade_id between", value1, value2, "gradeId");
			return (Criteria) this;
		}

		public Criteria andGradeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("grade_id not between", value1, value2, "gradeId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdIsNull() {
			addCriterion("semester_id is null");
			return (Criteria) this;
		}

		public Criteria andSemesterIdIsNotNull() {
			addCriterion("semester_id is not null");
			return (Criteria) this;
		}

		public Criteria andSemesterIdEqualTo(Integer value) {
			addCriterion("semester_id =", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdNotEqualTo(Integer value) {
			addCriterion("semester_id <>", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdGreaterThan(Integer value) {
			addCriterion("semester_id >", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("semester_id >=", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdLessThan(Integer value) {
			addCriterion("semester_id <", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdLessThanOrEqualTo(Integer value) {
			addCriterion("semester_id <=", value, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdIn(List<Integer> values) {
			addCriterion("semester_id in", values, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdNotIn(List<Integer> values) {
			addCriterion("semester_id not in", values, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdBetween(Integer value1, Integer value2) {
			addCriterion("semester_id between", value1, value2, "semesterId");
			return (Criteria) this;
		}

		public Criteria andSemesterIdNotBetween(Integer value1, Integer value2) {
			addCriterion("semester_id not between", value1, value2, "semesterId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdIsNull() {
			addCriterion("publisher_id is null");
			return (Criteria) this;
		}

		public Criteria andPublisherIdIsNotNull() {
			addCriterion("publisher_id is not null");
			return (Criteria) this;
		}

		public Criteria andPublisherIdEqualTo(Integer value) {
			addCriterion("publisher_id =", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdNotEqualTo(Integer value) {
			addCriterion("publisher_id <>", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdGreaterThan(Integer value) {
			addCriterion("publisher_id >", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("publisher_id >=", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdLessThan(Integer value) {
			addCriterion("publisher_id <", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdLessThanOrEqualTo(Integer value) {
			addCriterion("publisher_id <=", value, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdIn(List<Integer> values) {
			addCriterion("publisher_id in", values, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdNotIn(List<Integer> values) {
			addCriterion("publisher_id not in", values, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdBetween(Integer value1, Integer value2) {
			addCriterion("publisher_id between", value1, value2, "publisherId");
			return (Criteria) this;
		}

		public Criteria andPublisherIdNotBetween(Integer value1, Integer value2) {
			addCriterion("publisher_id not between", value1, value2, "publisherId");
			return (Criteria) this;
		}

		public Criteria andCourseNameIsNull() {
			addCriterion("course_name is null");
			return (Criteria) this;
		}

		public Criteria andCourseNameIsNotNull() {
			addCriterion("course_name is not null");
			return (Criteria) this;
		}

		public Criteria andCourseNameEqualTo(String value) {
			addCriterion("course_name =", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameNotEqualTo(String value) {
			addCriterion("course_name <>", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameGreaterThan(String value) {
			addCriterion("course_name >", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
			addCriterion("course_name >=", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameLessThan(String value) {
			addCriterion("course_name <", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameLessThanOrEqualTo(String value) {
			addCriterion("course_name <=", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameLike(String value) {
			addCriterion("course_name like", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameNotLike(String value) {
			addCriterion("course_name not like", value, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameIn(List<String> values) {
			addCriterion("course_name in", values, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameNotIn(List<String> values) {
			addCriterion("course_name not in", values, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameBetween(String value1, String value2) {
			addCriterion("course_name between", value1, value2, "courseName");
			return (Criteria) this;
		}

		public Criteria andCourseNameNotBetween(String value1, String value2) {
			addCriterion("course_name not between", value1, value2, "courseName");
			return (Criteria) this;
		}

		public Criteria andStudentCountIsNull() {
			addCriterion("student_count is null");
			return (Criteria) this;
		}

		public Criteria andStudentCountIsNotNull() {
			addCriterion("student_count is not null");
			return (Criteria) this;
		}

		public Criteria andStudentCountEqualTo(Integer value) {
			addCriterion("student_count =", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountNotEqualTo(Integer value) {
			addCriterion("student_count <>", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountGreaterThan(Integer value) {
			addCriterion("student_count >", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("student_count >=", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountLessThan(Integer value) {
			addCriterion("student_count <", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountLessThanOrEqualTo(Integer value) {
			addCriterion("student_count <=", value, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountIn(List<Integer> values) {
			addCriterion("student_count in", values, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountNotIn(List<Integer> values) {
			addCriterion("student_count not in", values, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountBetween(Integer value1, Integer value2) {
			addCriterion("student_count between", value1, value2, "studentCount");
			return (Criteria) this;
		}

		public Criteria andStudentCountNotBetween(Integer value1, Integer value2) {
			addCriterion("student_count not between", value1, value2, "studentCount");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterionForJDBCDate("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterionForJDBCDate("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterionForJDBCDate("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterionForJDBCDate("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table youranxue.course_trn
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table youranxue.course_trn
     *
     * @mbg.generated do_not_delete_during_merge Sun May 13 21:08:22 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}