package com.youranxue.domain.model;

import java.util.Date;

public class CourseTrn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.course_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String courseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.subject_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer subjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.grade_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer gradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.semester_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer semesterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.publisher_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer publisherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.course_name
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String courseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.student_count
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer studentCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.end_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.course_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.course_id
	 * @return  the value of youranxue.course_trn.course_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.course_id
	 * @param courseId  the value for youranxue.course_trn.course_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.subject_id
	 * @return  the value of youranxue.course_trn.subject_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.subject_id
	 * @param subjectId  the value for youranxue.course_trn.subject_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.grade_id
	 * @return  the value of youranxue.course_trn.grade_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getGradeId() {
		return gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.grade_id
	 * @param gradeId  the value for youranxue.course_trn.grade_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.semester_id
	 * @return  the value of youranxue.course_trn.semester_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getSemesterId() {
		return semesterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.semester_id
	 * @param semesterId  the value for youranxue.course_trn.semester_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setSemesterId(Integer semesterId) {
		this.semesterId = semesterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.publisher_id
	 * @return  the value of youranxue.course_trn.publisher_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getPublisherId() {
		return publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.publisher_id
	 * @param publisherId  the value for youranxue.course_trn.publisher_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.course_name
	 * @return  the value of youranxue.course_trn.course_name
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getCourseName() {
		return courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.course_name
	 * @param courseName  the value for youranxue.course_trn.course_name
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.student_count
	 * @return  the value of youranxue.course_trn.student_count
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getStudentCount() {
		return studentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.student_count
	 * @param studentCount  the value for youranxue.course_trn.student_count
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setStudentCount(Integer studentCount) {
		this.studentCount = studentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.end_date
	 * @return  the value of youranxue.course_trn.end_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.end_date
	 * @param endDate  the value for youranxue.course_trn.end_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.status
	 * @return  the value of youranxue.course_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.status
	 * @param status  the value for youranxue.course_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.create_date
	 * @return  the value of youranxue.course_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.create_date
	 * @param createDate  the value for youranxue.course_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.update_date
	 * @return  the value of youranxue.course_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.update_date
	 * @param updateDate  the value for youranxue.course_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.course_trn.update_user
	 * @return  the value of youranxue.course_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.course_trn.update_user
	 * @param updateUser  the value for youranxue.course_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}