package com.youranxue.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ImgMstExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public ImgMstExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andImgIdIsNull() {
			addCriterion("img_id is null");
			return (Criteria) this;
		}

		public Criteria andImgIdIsNotNull() {
			addCriterion("img_id is not null");
			return (Criteria) this;
		}

		public Criteria andImgIdEqualTo(Integer value) {
			addCriterion("img_id =", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotEqualTo(Integer value) {
			addCriterion("img_id <>", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdGreaterThan(Integer value) {
			addCriterion("img_id >", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("img_id >=", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdLessThan(Integer value) {
			addCriterion("img_id <", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdLessThanOrEqualTo(Integer value) {
			addCriterion("img_id <=", value, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdIn(List<Integer> values) {
			addCriterion("img_id in", values, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotIn(List<Integer> values) {
			addCriterion("img_id not in", values, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdBetween(Integer value1, Integer value2) {
			addCriterion("img_id between", value1, value2, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgIdNotBetween(Integer value1, Integer value2) {
			addCriterion("img_id not between", value1, value2, "imgId");
			return (Criteria) this;
		}

		public Criteria andImgTypeIsNull() {
			addCriterion("img_type is null");
			return (Criteria) this;
		}

		public Criteria andImgTypeIsNotNull() {
			addCriterion("img_type is not null");
			return (Criteria) this;
		}

		public Criteria andImgTypeEqualTo(Short value) {
			addCriterion("img_type =", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeNotEqualTo(Short value) {
			addCriterion("img_type <>", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeGreaterThan(Short value) {
			addCriterion("img_type >", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("img_type >=", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeLessThan(Short value) {
			addCriterion("img_type <", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeLessThanOrEqualTo(Short value) {
			addCriterion("img_type <=", value, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeIn(List<Short> values) {
			addCriterion("img_type in", values, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeNotIn(List<Short> values) {
			addCriterion("img_type not in", values, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeBetween(Short value1, Short value2) {
			addCriterion("img_type between", value1, value2, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgTypeNotBetween(Short value1, Short value2) {
			addCriterion("img_type not between", value1, value2, "imgType");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdIsNull() {
			addCriterion("img_releation_id is null");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdIsNotNull() {
			addCriterion("img_releation_id is not null");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdEqualTo(Long value) {
			addCriterion("img_releation_id =", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdNotEqualTo(Long value) {
			addCriterion("img_releation_id <>", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdGreaterThan(Long value) {
			addCriterion("img_releation_id >", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdGreaterThanOrEqualTo(Long value) {
			addCriterion("img_releation_id >=", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdLessThan(Long value) {
			addCriterion("img_releation_id <", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdLessThanOrEqualTo(Long value) {
			addCriterion("img_releation_id <=", value, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdIn(List<Long> values) {
			addCriterion("img_releation_id in", values, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdNotIn(List<Long> values) {
			addCriterion("img_releation_id not in", values, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdBetween(Long value1, Long value2) {
			addCriterion("img_releation_id between", value1, value2, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgReleationIdNotBetween(Long value1, Long value2) {
			addCriterion("img_releation_id not between", value1, value2, "imgReleationId");
			return (Criteria) this;
		}

		public Criteria andImgNameIsNull() {
			addCriterion("img_name is null");
			return (Criteria) this;
		}

		public Criteria andImgNameIsNotNull() {
			addCriterion("img_name is not null");
			return (Criteria) this;
		}

		public Criteria andImgNameEqualTo(String value) {
			addCriterion("img_name =", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameNotEqualTo(String value) {
			addCriterion("img_name <>", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameGreaterThan(String value) {
			addCriterion("img_name >", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameGreaterThanOrEqualTo(String value) {
			addCriterion("img_name >=", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameLessThan(String value) {
			addCriterion("img_name <", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameLessThanOrEqualTo(String value) {
			addCriterion("img_name <=", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameLike(String value) {
			addCriterion("img_name like", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameNotLike(String value) {
			addCriterion("img_name not like", value, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameIn(List<String> values) {
			addCriterion("img_name in", values, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameNotIn(List<String> values) {
			addCriterion("img_name not in", values, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameBetween(String value1, String value2) {
			addCriterion("img_name between", value1, value2, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgNameNotBetween(String value1, String value2) {
			addCriterion("img_name not between", value1, value2, "imgName");
			return (Criteria) this;
		}

		public Criteria andImgPathIsNull() {
			addCriterion("img_path is null");
			return (Criteria) this;
		}

		public Criteria andImgPathIsNotNull() {
			addCriterion("img_path is not null");
			return (Criteria) this;
		}

		public Criteria andImgPathEqualTo(String value) {
			addCriterion("img_path =", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathNotEqualTo(String value) {
			addCriterion("img_path <>", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathGreaterThan(String value) {
			addCriterion("img_path >", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathGreaterThanOrEqualTo(String value) {
			addCriterion("img_path >=", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathLessThan(String value) {
			addCriterion("img_path <", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathLessThanOrEqualTo(String value) {
			addCriterion("img_path <=", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathLike(String value) {
			addCriterion("img_path like", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathNotLike(String value) {
			addCriterion("img_path not like", value, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathIn(List<String> values) {
			addCriterion("img_path in", values, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathNotIn(List<String> values) {
			addCriterion("img_path not in", values, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathBetween(String value1, String value2) {
			addCriterion("img_path between", value1, value2, "imgPath");
			return (Criteria) this;
		}

		public Criteria andImgPathNotBetween(String value1, String value2) {
			addCriterion("img_path not between", value1, value2, "imgPath");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table youranxue.img_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table youranxue.img_mst
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 06 20:59:03 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}