package com.youranxue.domain.model;

import java.util.Date;

public class ImgMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.img_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer imgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.img_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Short imgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.img_releation_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Long imgReleationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.img_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String imgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.img_path
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.img_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.img_id
	 * @return  the value of youranxue.img_mst.img_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getImgId() {
		return imgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.img_id
	 * @param imgId  the value for youranxue.img_mst.img_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setImgId(Integer imgId) {
		this.imgId = imgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.img_type
	 * @return  the value of youranxue.img_mst.img_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Short getImgType() {
		return imgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.img_type
	 * @param imgType  the value for youranxue.img_mst.img_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setImgType(Short imgType) {
		this.imgType = imgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.img_releation_id
	 * @return  the value of youranxue.img_mst.img_releation_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Long getImgReleationId() {
		return imgReleationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.img_releation_id
	 * @param imgReleationId  the value for youranxue.img_mst.img_releation_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setImgReleationId(Long imgReleationId) {
		this.imgReleationId = imgReleationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.img_name
	 * @return  the value of youranxue.img_mst.img_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getImgName() {
		return imgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.img_name
	 * @param imgName  the value for youranxue.img_mst.img_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.img_path
	 * @return  the value of youranxue.img_mst.img_path
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.img_path
	 * @param imgPath  the value for youranxue.img_mst.img_path
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.create_date
	 * @return  the value of youranxue.img_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.create_date
	 * @param createDate  the value for youranxue.img_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.update_date
	 * @return  the value of youranxue.img_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.update_date
	 * @param updateDate  the value for youranxue.img_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.img_mst.update_user
	 * @return  the value of youranxue.img_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.img_mst.update_user
	 * @param updateUser  the value for youranxue.img_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}