package com.youranxue.domain.model;

import java.util.Date;

import ch.qos.logback.core.net.SyslogOutputStream;

public class MyBooks {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_books.my_book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	private Integer myBookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_books.book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	private Integer bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_books.create_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_books.update_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.my_books.update_user
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_books.my_book_id
	 * @return  the value of public.my_books.my_book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public Integer getMyBookId() {
		return myBookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_books.my_book_id
	 * @param myBookId  the value for public.my_books.my_book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public void setMyBookId(Integer myBookId) {
		this.myBookId = myBookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_books.book_id
	 * @return  the value of public.my_books.book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public Integer getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_books.book_id
	 * @param bookId  the value for public.my_books.book_id
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_books.create_date
	 * @return  the value of public.my_books.create_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_books.create_date
	 * @param createDate  the value for public.my_books.create_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_books.update_date
	 * @return  the value of public.my_books.update_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_books.update_date
	 * @param updateDate  the value for public.my_books.update_date
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.my_books.update_user
	 * @return  the value of public.my_books.update_user
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.my_books.update_user
	 * @param updateUser  the value for public.my_books.update_user
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}