package com.youranxue.domain.model;

import java.util.Date;

public class TestGroupTrn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.test_group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Long testGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.test_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Long testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.test_type_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Integer testTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.start_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.end_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_group_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.test_group_id
	 * @return  the value of youranxue.test_group_trn.test_group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Long getTestGroupId() {
		return testGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.test_group_id
	 * @param testGroupId  the value for youranxue.test_group_trn.test_group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setTestGroupId(Long testGroupId) {
		this.testGroupId = testGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.group_id
	 * @return  the value of youranxue.test_group_trn.group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.group_id
	 * @param groupId  the value for youranxue.test_group_trn.group_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.test_id
	 * @return  the value of youranxue.test_group_trn.test_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Long getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.test_id
	 * @param testId  the value for youranxue.test_group_trn.test_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setTestId(Long testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.test_type_id
	 * @return  the value of youranxue.test_group_trn.test_type_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Integer getTestTypeId() {
		return testTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.test_type_id
	 * @param testTypeId  the value for youranxue.test_group_trn.test_type_id
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setTestTypeId(Integer testTypeId) {
		this.testTypeId = testTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.start_time
	 * @return  the value of youranxue.test_group_trn.start_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.start_time
	 * @param startTime  the value for youranxue.test_group_trn.start_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.end_time
	 * @return  the value of youranxue.test_group_trn.end_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.end_time
	 * @param endTime  the value for youranxue.test_group_trn.end_time
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.status
	 * @return  the value of youranxue.test_group_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.status
	 * @param status  the value for youranxue.test_group_trn.status
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.create_date
	 * @return  the value of youranxue.test_group_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.create_date
	 * @param createDate  the value for youranxue.test_group_trn.create_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.update_date
	 * @return  the value of youranxue.test_group_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.update_date
	 * @param updateDate  the value for youranxue.test_group_trn.update_date
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_group_trn.update_user
	 * @return  the value of youranxue.test_group_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_group_trn.update_user
	 * @param updateUser  the value for youranxue.test_group_trn.update_user
	 * @mbg.generated  Sat Jun 09 20:41:13 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}