package com.youranxue.domain.mapper;

import com.youranxue.domain.model.MyBooks;
import com.youranxue.domain.model.MyBooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyBooksMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	long countByExample(MyBooksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int deleteByExample(MyBooksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int deleteByPrimaryKey(Integer myBookId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int insert(MyBooks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int insertSelective(MyBooks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	List<MyBooks> selectByExample(MyBooksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	MyBooks selectByPrimaryKey(Integer myBookId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int updateByExampleSelective(@Param("record") MyBooks record, @Param("example") MyBooksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int updateByExample(@Param("record") MyBooks record, @Param("example") MyBooksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int updateByPrimaryKeySelective(MyBooks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.my_books
	 * @mbg.generated  Sun Aug 26 15:45:00 JST 2018
	 */
	int updateByPrimaryKey(MyBooks record);
}