package com.youranxue.domain.mapper;

import com.youranxue.domain.model.SectionMst;
import com.youranxue.domain.model.SectionMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionMstMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	long countByExample(SectionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int deleteByExample(SectionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int deleteByPrimaryKey(Integer sectionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int insert(SectionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int insertSelective(SectionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	List<SectionMst> selectByExample(SectionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	SectionMst selectByPrimaryKey(Integer sectionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int updateByExampleSelective(@Param("record") SectionMst record, @Param("example") SectionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int updateByExample(@Param("record") SectionMst record, @Param("example") SectionMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int updateByPrimaryKeySelective(SectionMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table youranxue.section_mst
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	int updateByPrimaryKey(SectionMst record);
}