package com.youranxue.domain.model;

import java.util.Date;

public class ChapterMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer chapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.chapter_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String chapterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.book_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.chapter_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.chapter_id
	 * @return  the value of youranxue.chapter_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getChapterId() {
		return chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.chapter_id
	 * @param chapterId  the value for youranxue.chapter_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.chapter_name
	 * @return  the value of youranxue.chapter_mst.chapter_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getChapterName() {
		return chapterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.chapter_name
	 * @param chapterName  the value for youranxue.chapter_mst.chapter_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.book_id
	 * @return  the value of youranxue.chapter_mst.book_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.book_id
	 * @param bookId  the value for youranxue.chapter_mst.book_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.create_date
	 * @return  the value of youranxue.chapter_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.create_date
	 * @param createDate  the value for youranxue.chapter_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.update_date
	 * @return  the value of youranxue.chapter_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.update_date
	 * @param updateDate  the value for youranxue.chapter_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.chapter_mst.update_user
	 * @return  the value of youranxue.chapter_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.chapter_mst.update_user
	 * @param updateUser  the value for youranxue.chapter_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}