package com.youranxue.domain.model;

import java.util.Date;

public class Question {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.question_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer questionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.question_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Short questionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.question
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.question.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.question_id
	 * @return  the value of youranxue.question.question_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.question_id
	 * @param questionId  the value for youranxue.question.question_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.question_type
	 * @return  the value of youranxue.question.question_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Short getQuestionType() {
		return questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.question_type
	 * @param questionType  the value for youranxue.question.question_type
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setQuestionType(Short questionType) {
		this.questionType = questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.question
	 * @return  the value of youranxue.question.question
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.question
	 * @param question  the value for youranxue.question.question
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.create_date
	 * @return  the value of youranxue.question.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.create_date
	 * @param createDate  the value for youranxue.question.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.update_date
	 * @return  the value of youranxue.question.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.update_date
	 * @param updateDate  the value for youranxue.question.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.question.update_user
	 * @return  the value of youranxue.question.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.question.update_user
	 * @param updateUser  the value for youranxue.question.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}