package com.youranxue.domain.model;

public class SchoolMst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.school_mst.school_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.school_mst.school_name
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youranxue.school_mst.address_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    private Long addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.school_mst.school_id
     *
     * @return the value of youranxue.school_mst.school_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.school_mst.school_id
     *
     * @param schoolId the value for youranxue.school_mst.school_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.school_mst.school_name
     *
     * @return the value of youranxue.school_mst.school_name
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.school_mst.school_name
     *
     * @param schoolName the value for youranxue.school_mst.school_name
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youranxue.school_mst.address_id
     *
     * @return the value of youranxue.school_mst.address_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youranxue.school_mst.address_id
     *
     * @param addressId the value for youranxue.school_mst.address_id
     *
     * @mbg.generated Mon Dec 04 06:12:14 JST 2017
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
}