package com.youranxue.domain.model;

import java.util.Date;

public class SectionMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.section_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer sectionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Integer chapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.section_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String sectionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.section_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.section_id
	 * @return  the value of youranxue.section_mst.section_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getSectionId() {
		return sectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.section_id
	 * @param sectionId  the value for youranxue.section_mst.section_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.chapter_id
	 * @return  the value of youranxue.section_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Integer getChapterId() {
		return chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.chapter_id
	 * @param chapterId  the value for youranxue.section_mst.chapter_id
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.section_name
	 * @return  the value of youranxue.section_mst.section_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getSectionName() {
		return sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.section_name
	 * @param sectionName  the value for youranxue.section_mst.section_name
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.create_date
	 * @return  the value of youranxue.section_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.create_date
	 * @param createDate  the value for youranxue.section_mst.create_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.update_date
	 * @return  the value of youranxue.section_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.update_date
	 * @param updateDate  the value for youranxue.section_mst.update_date
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.section_mst.update_user
	 * @return  the value of youranxue.section_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.section_mst.update_user
	 * @param updateUser  the value for youranxue.section_mst.update_user
	 * @mbg.generated  Sun Mar 18 16:04:02 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}