package com.youranxue.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class TestTrn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.test_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Long testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.chapter_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Integer chapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.section_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Integer sectionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.test_name
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private String testName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.total_score
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Integer totalScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.test_duration_min
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Integer testDurationMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.create_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.update_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column youranxue.test_trn.update_user
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.test_id
	 * @return  the value of youranxue.test_trn.test_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Long getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.test_id
	 * @param testId  the value for youranxue.test_trn.test_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setTestId(Long testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.chapter_id
	 * @return  the value of youranxue.test_trn.chapter_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Integer getChapterId() {
		return chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.chapter_id
	 * @param chapterId  the value for youranxue.test_trn.chapter_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.section_id
	 * @return  the value of youranxue.test_trn.section_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Integer getSectionId() {
		return sectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.section_id
	 * @param sectionId  the value for youranxue.test_trn.section_id
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setSectionId(Integer sectionId) {
		this.sectionId = sectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.test_name
	 * @return  the value of youranxue.test_trn.test_name
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public String getTestName() {
		return testName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.test_name
	 * @param testName  the value for youranxue.test_trn.test_name
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setTestName(String testName) {
		this.testName = testName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.total_score
	 * @return  the value of youranxue.test_trn.total_score
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Integer getTotalScore() {
		return totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.total_score
	 * @param totalScore  the value for youranxue.test_trn.total_score
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setTotalScore(Integer totalScore) {
		this.totalScore = totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.test_duration_min
	 * @return  the value of youranxue.test_trn.test_duration_min
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Integer getTestDurationMin() {
		return testDurationMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.test_duration_min
	 * @param testDurationMin  the value for youranxue.test_trn.test_duration_min
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setTestDurationMin(Integer testDurationMin) {
		this.testDurationMin = testDurationMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.create_date
	 * @return  the value of youranxue.test_trn.create_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.create_date
	 * @param createDate  the value for youranxue.test_trn.create_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.update_date
	 * @return  the value of youranxue.test_trn.update_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.update_date
	 * @param updateDate  the value for youranxue.test_trn.update_date
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column youranxue.test_trn.update_user
	 * @return  the value of youranxue.test_trn.update_user
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column youranxue.test_trn.update_user
	 * @param updateUser  the value for youranxue.test_trn.update_user
	 * @mbg.generated  Sun Jun 03 02:01:20 JST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}